from __future__ import annotations

CANDIDATE_SOURCE_SEPARATOR = "separator_candidate"
CANDIDATE_SOURCE_CONTENT = "content_candidate"
CANDIDATE_SOURCE_HARD_SAFETY = "hard_safety"
CANDIDATE_SOURCE_REVIEW_ONLY = "review_only_mode"
CANDIDATE_SOURCE_DUAL_LANE = "dual_lane_strip"

FINAL_REASON_FRAME_TOPOLOGY_INVALID = "frame_topology_invalid"
FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED = "content_preservation_unresolved"
FINAL_REASON_BOUNDARY_EVIDENCE_INSUFFICIENT = "boundary_evidence_insufficient"
FINAL_REASON_PHOTO_GEOMETRY_CONTRADICTED = "photo_geometry_contradicted"
FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED = "evidence_independence_failed"
FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT = "selection_geometry_disagreement"
FINAL_REASON_OUTPUT_PROTECTION_UNRESOLVED = "output_protection_unresolved"
FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN = "transform_geometry_uncertain"
FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED = "automatic_processing_not_supported"

FINAL_REVIEW_REASONS = frozenset(
    {
        FINAL_REASON_FRAME_TOPOLOGY_INVALID,
        FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED,
        FINAL_REASON_BOUNDARY_EVIDENCE_INSUFFICIENT,
        FINAL_REASON_PHOTO_GEOMETRY_CONTRADICTED,
        FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED,
        FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT,
        FINAL_REASON_OUTPUT_PROTECTION_UNRESOLVED,
        FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN,
        FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED,
    }
)

GAP_DETECTED = "detected"
GAP_EDGE_PAIR = "edge-pair"
GAP_GRID = "grid"
GAP_EQUAL = "equal"
GAP_CONTENT = "content"

HARD_GAP_METHODS = frozenset({
    GAP_DETECTED,
    GAP_EDGE_PAIR,
})
MODEL_GAP_METHODS = frozenset({
    GAP_GRID,
    GAP_EQUAL,
    GAP_CONTENT,
})
