from __future__ import annotations

CANDIDATE_SOURCE_FRAME_SEQUENCE = "frame_sequence"
CANDIDATE_SOURCE_HARD_SAFETY = "hard_safety"
CANDIDATE_SOURCE_REVIEW_ONLY = "review_only_mode"
CANDIDATE_SOURCE_DUAL_LANE = "dual_lane_strip"

FINAL_REASON_FRAME_TOPOLOGY_INVALID = "frame_topology_invalid"
FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED = "content_preservation_unresolved"
FINAL_REASON_BOUNDARY_EVIDENCE_INSUFFICIENT = "boundary_evidence_insufficient"
FINAL_REASON_PHOTO_GEOMETRY_CONTRADICTED = "photo_geometry_contradicted"
FINAL_REASON_FRAME_SEQUENCE_NOT_CONSERVED = "frame_sequence_not_conserved"
FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED = "evidence_independence_failed"
FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT = "selection_geometry_disagreement"
FINAL_REASON_OUTPUT_BLEED_UNRESOLVED = "output_bleed_unresolved"
FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN = "transform_geometry_uncertain"
FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED = "automatic_processing_not_supported"
FINAL_REASON_COUNT_RESOLUTION_UNAVAILABLE = "count_resolution_unavailable"
FINAL_REASON_GEOMETRY_RESOLUTION_UNAVAILABLE = "geometry_resolution_unavailable"

FINAL_REVIEW_REASONS = frozenset(
    {
        FINAL_REASON_FRAME_TOPOLOGY_INVALID,
        FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED,
        FINAL_REASON_BOUNDARY_EVIDENCE_INSUFFICIENT,
        FINAL_REASON_PHOTO_GEOMETRY_CONTRADICTED,
        FINAL_REASON_FRAME_SEQUENCE_NOT_CONSERVED,
        FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED,
        FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT,
        FINAL_REASON_OUTPUT_BLEED_UNRESOLVED,
        FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN,
        FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED,
        FINAL_REASON_COUNT_RESOLUTION_UNAVAILABLE,
        FINAL_REASON_GEOMETRY_RESOLUTION_UNAVAILABLE,
    }
)
