MAX_BANDS_PER_CORRIDOR = 4
MAX_COMPLETE_CHAINS_PER_LANE = 8
MAX_LEDGER_ENTRIES_PER_CHAIN = 64
MAX_LEDGER_ENTRIES_PER_LANE = 512
MAX_LEDGER_ENTRIES_PER_SOURCE = 1024
MAX_CONTENT_VETO_FACTS_PER_CHAIN = 64
