from __future__ import annotations

from ..candidate.assessment.model import CandidateGateAssessment
from ..gate_checks import GateCheck, GateGap, GateStage
from .model import DecisionGateAssessment
from .vocabulary import (
    FINAL_REASON_CONTENT_PROTECTION_CONFLICT,
    FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED,
    FINAL_REASON_LOCAL_ADVANCE_UNRESOLVED,
    FINAL_REASON_NO_LEGAL_PLACEMENT,
    FINAL_REASON_PLACEMENT_UNRESOLVED,
    FINAL_REASON_PRODUCER_BOUND_EXCEEDED,
    FINAL_REASON_SOURCE_LANE_AUTHORITY_UNAVAILABLE,
    FINAL_REASON_TRANSFORM_SAMPLING_UNAVAILABLE,
)


_REASON_BY_GAP = {
    GateGap.SCAN_CANVAS_AUTHORITY_UNAVAILABLE: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.HOLDER_FULL_COUNT_UNRESOLVED: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.HOLDER_IDENTITY_UNRESOLVED: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.OUTPUT_SLOT_COUNT_UNAVAILABLE: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.COMPLETE_CHAIN_UNAVAILABLE: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.SHARED_STRIP_DIRECTION_UNAVAILABLE: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.SHARED_STRIP_DIRECTION_NONUNIQUE: FINAL_REASON_PLACEMENT_UNRESOLVED,
    GateGap.SOURCE_SCAN_GEOMETRY_UNAVAILABLE: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.PLACEMENT_UNRESOLVED: FINAL_REASON_PLACEMENT_UNRESOLVED,
    GateGap.CONTENT_VETO_REJECTED: FINAL_REASON_CONTENT_PROTECTION_CONFLICT,
    GateGap.LOCAL_ADVANCE_UNRESOLVED: FINAL_REASON_LOCAL_ADVANCE_UNRESOLVED,
    GateGap.SLOT_ORDINAL_ASSIGNMENT_UNRESOLVED: FINAL_REASON_NO_LEGAL_PLACEMENT,
    GateGap.SOURCE_LANE_AUTHORITY_INVALID: (
        FINAL_REASON_SOURCE_LANE_AUTHORITY_UNAVAILABLE
    ),
    GateGap.SELECTED_PLACEMENT_CONTAINMENT_UNAVAILABLE: (
        FINAL_REASON_TRANSFORM_SAMPLING_UNAVAILABLE
    ),
    GateGap.PRODUCER_BOUND_EXCEEDED: FINAL_REASON_PRODUCER_BOUND_EXCEEDED,
    GateGap.DIRECT_USE_BUDGET_EXCEEDED: (
        FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED
    ),
    GateGap.DIRECT_USE_BUDGET_UNAVAILABLE: (
        FINAL_REASON_NO_LEGAL_PLACEMENT
    ),
    GateGap.OUTPUT_TRANSFORM_UNAVAILABLE: (
        FINAL_REASON_TRANSFORM_SAMPLING_UNAVAILABLE
    ),
}


def apply_decision_gate(
    candidate_gate: CandidateGateAssessment,
) -> DecisionGateAssessment:
    return DecisionGateAssessment(
        checks=tuple(
            GateCheck(
                code=check.code,
                stage=GateStage.DECISION,
                state=check.state,
                gap=check.gap,
                final_review_reason=(
                    _REASON_BY_GAP[check.gap]
                    if check.blocks and check.gap is not None
                    else None
                ),
            )
            for check in candidate_gate.checks
        )
    )
