from __future__ import annotations


FINAL_REASON_CONTENT_ONLY_EVIDENCE = "content_only_evidence"
FINAL_REASON_EVIDENCE_INSUFFICIENT = "evidence_combination_insufficient"
FINAL_REASON_OUTER_CONTENT_MISMATCH = "outer_content_mismatch"
FINAL_REASON_SEPARATOR_INCOMPLETE = "separator_evidence_incomplete"
FINAL_REASON_GEOMETRY_UNSTABLE = "geometry_unstable"
FINAL_REASON_CONTENT_INSUFFICIENT = "content_evidence_insufficient"
FINAL_REASON_CANDIDATE_COMPETITION_CLOSE = "candidate_competition_close"
FINAL_REASON_EXPOSURE_OVERLAP_UNRESOLVED = "exposure_overlap_unresolved"
FINAL_REASON_PARTIAL_EDGE_UNCERTAIN = "partial_edge_uncertain"
FINAL_REASON_OUTER_CANDIDATE_DISAGREEMENT = "outer_candidate_disagreement"
FINAL_REASON_DESKEW_UNCERTAIN = "deskew_uncertain"
