from __future__ import annotations


FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED = "content_preservation_unresolved"
FINAL_REASON_FRAME_SLOT_TOPOLOGY_INVALID = "frame_slot_topology_invalid"
FINAL_REASON_SEQUENCE_EVIDENCE_INSUFFICIENT = "sequence_evidence_insufficient"
FINAL_REASON_FRAME_DIMENSION_CONTRADICTED = "frame_dimension_contradicted"
FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED = "evidence_independence_failed"
FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT = "selection_geometry_disagreement"
FINAL_REASON_OUTPUT_PROTECTION_UNRESOLVED = "output_protection_unresolved"
FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN = "transform_geometry_uncertain"
FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED = "automatic_processing_not_supported"
FINAL_REASON_COUNT_RESOLUTION_UNAVAILABLE = "count_resolution_unavailable"
FINAL_REASON_GEOMETRY_RESOLUTION_UNAVAILABLE = "geometry_resolution_unavailable"


FINAL_REVIEW_REASONS = frozenset(
    {
        FINAL_REASON_CONTENT_PRESERVATION_UNRESOLVED,
        FINAL_REASON_FRAME_SLOT_TOPOLOGY_INVALID,
        FINAL_REASON_SEQUENCE_EVIDENCE_INSUFFICIENT,
        FINAL_REASON_FRAME_DIMENSION_CONTRADICTED,
        FINAL_REASON_EVIDENCE_INDEPENDENCE_FAILED,
        FINAL_REASON_SELECTION_GEOMETRY_DISAGREEMENT,
        FINAL_REASON_OUTPUT_PROTECTION_UNRESOLVED,
        FINAL_REASON_TRANSFORM_GEOMETRY_UNCERTAIN,
        FINAL_REASON_AUTOMATIC_PROCESSING_NOT_SUPPORTED,
        FINAL_REASON_COUNT_RESOLUTION_UNAVAILABLE,
        FINAL_REASON_GEOMETRY_RESOLUTION_UNAVAILABLE,
    }
)
