from __future__ import annotations


FINAL_REASON_SCAN_CANVAS_AUTHORITY_UNAVAILABLE = (
    "scan_canvas_authority_unavailable"
)
FINAL_REASON_HOLDER_FULL_COUNT_UNRESOLVED = "holder_full_count_unresolved"
FINAL_REASON_HOLDER_IDENTITY_UNRESOLVED = "holder_identity_unresolved"
FINAL_REASON_REQUESTED_COUNT_UNFULFILLED = "requested_count_unfulfilled"
FINAL_REASON_COMPLETE_CHAIN_UNAVAILABLE = "complete_chain_unavailable"
FINAL_REASON_PRODUCER_BOUND_EXCEEDED = "producer_bound_exceeded"
FINAL_REASON_SHARED_STRIP_DIRECTION_UNAVAILABLE = (
    "shared_strip_direction_unavailable"
)
FINAL_REASON_SHARED_STRIP_DIRECTION_NONUNIQUE = (
    "shared_strip_direction_nonunique"
)
FINAL_REASON_SOURCE_FRAME_GEOMETRY_UNAVAILABLE = (
    "source_frame_geometry_unavailable"
)
FINAL_REASON_PLACEMENT_UNRESOLVED = "placement_unresolved"
FINAL_REASON_CONTENT_VETO_REJECTED = "content_veto_rejected"
FINAL_REASON_SLOT_ORDINAL_ASSIGNMENT_UNRESOLVED = (
    "slot_ordinal_assignment_unresolved"
)
FINAL_REASON_SOURCE_LANE_AUTHORITY_INVALID = "source_lane_authority_invalid"
FINAL_REASON_SELECTED_PLACEMENT_CONTAINMENT_UNAVAILABLE = (
    "selected_placement_containment_unavailable"
)
FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED = "direct_use_budget_exceeded"
FINAL_REASON_DIRECT_USE_BUDGET_UNAVAILABLE = "direct_use_budget_unavailable"
FINAL_REASON_OUTPUT_TRANSFORM_UNAVAILABLE = "output_transform_unavailable"


FINAL_REVIEW_REASONS = frozenset(
    {
        FINAL_REASON_SCAN_CANVAS_AUTHORITY_UNAVAILABLE,
        FINAL_REASON_HOLDER_FULL_COUNT_UNRESOLVED,
        FINAL_REASON_HOLDER_IDENTITY_UNRESOLVED,
        FINAL_REASON_REQUESTED_COUNT_UNFULFILLED,
        FINAL_REASON_COMPLETE_CHAIN_UNAVAILABLE,
        FINAL_REASON_PRODUCER_BOUND_EXCEEDED,
        FINAL_REASON_SHARED_STRIP_DIRECTION_UNAVAILABLE,
        FINAL_REASON_SHARED_STRIP_DIRECTION_NONUNIQUE,
        FINAL_REASON_SOURCE_FRAME_GEOMETRY_UNAVAILABLE,
        FINAL_REASON_PLACEMENT_UNRESOLVED,
        FINAL_REASON_CONTENT_VETO_REJECTED,
        FINAL_REASON_SLOT_ORDINAL_ASSIGNMENT_UNRESOLVED,
        FINAL_REASON_SOURCE_LANE_AUTHORITY_INVALID,
        FINAL_REASON_SELECTED_PLACEMENT_CONTAINMENT_UNAVAILABLE,
        FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED,
        FINAL_REASON_DIRECT_USE_BUDGET_UNAVAILABLE,
        FINAL_REASON_OUTPUT_TRANSFORM_UNAVAILABLE,
    }
)
