from __future__ import annotations


FINAL_REASON_SCAN_CANVAS_AUTHORITY_UNAVAILABLE = (
    "scan_canvas_authority_unavailable"
)
FINAL_REASON_REQUESTED_COUNT_UNFULFILLED = "requested_count_unfulfilled"
FINAL_REASON_CAPACITY_OUTPUT_SLOT_COUNT_UNFULFILLED = (
    "capacity_output_slot_count_unfulfilled"
)
FINAL_REASON_FORMAT_PLACEMENT_UNAVAILABLE = "format_placement_unavailable"
FINAL_REASON_SHARED_STRIP_DIRECTION_UNAVAILABLE = (
    "shared_strip_direction_unavailable"
)
FINAL_REASON_SHARED_STRIP_DIRECTION_NONUNIQUE = (
    "shared_strip_direction_nonunique"
)
FINAL_REASON_SOURCE_FRAME_GEOMETRY_UNAVAILABLE = (
    "source_frame_geometry_unavailable"
)
FINAL_REASON_SLOT_ORDINAL_ASSIGNMENT_UNRESOLVED = (
    "slot_ordinal_assignment_unresolved"
)
FINAL_REASON_SOURCE_LANE_AUTHORITY_INVALID = "source_lane_authority_invalid"
FINAL_REASON_PLACEMENT_SET_CONTAINMENT_UNAVAILABLE = (
    "placement_set_containment_unavailable"
)
FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED = "direct_use_budget_exceeded"
FINAL_REASON_DIRECT_USE_BUDGET_UNAVAILABLE = "direct_use_budget_unavailable"
FINAL_REASON_OUTPUT_TRANSFORM_UNAVAILABLE = "output_transform_unavailable"


FINAL_REVIEW_REASONS = frozenset(
    {
        FINAL_REASON_SCAN_CANVAS_AUTHORITY_UNAVAILABLE,
        FINAL_REASON_REQUESTED_COUNT_UNFULFILLED,
        FINAL_REASON_CAPACITY_OUTPUT_SLOT_COUNT_UNFULFILLED,
        FINAL_REASON_FORMAT_PLACEMENT_UNAVAILABLE,
        FINAL_REASON_SHARED_STRIP_DIRECTION_UNAVAILABLE,
        FINAL_REASON_SHARED_STRIP_DIRECTION_NONUNIQUE,
        FINAL_REASON_SOURCE_FRAME_GEOMETRY_UNAVAILABLE,
        FINAL_REASON_SLOT_ORDINAL_ASSIGNMENT_UNRESOLVED,
        FINAL_REASON_SOURCE_LANE_AUTHORITY_INVALID,
        FINAL_REASON_PLACEMENT_SET_CONTAINMENT_UNAVAILABLE,
        FINAL_REASON_DIRECT_USE_BUDGET_EXCEEDED,
        FINAL_REASON_DIRECT_USE_BUDGET_UNAVAILABLE,
        FINAL_REASON_OUTPUT_TRANSFORM_UNAVAILABLE,
    }
)
