from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .base import DetectionPolicy


def detection_policy_report_detail(policy: "DetectionPolicy") -> dict[str, Any]:
    return {
        "policy_id": policy.policy_id,
        "format": policy.format_id,
        "strip_mode": policy.strip_mode,
        "family": policy.family,
        "role": policy.role,
        "detector": {
            "kind": policy.detector.kind,
            "dual_lane": {
                "lane_count": policy.detector.dual_lane.lane_count,
                "lane_format": policy.detector.dual_lane.lane_format,
                "unsupported_partial_reason": policy.detector.dual_lane.unsupported_partial_reason,
            },
        },
        "outer": {
            "content_floating": policy.outer.content_floating,
            "edge_anchor": policy.outer.edge_anchor,
            "base_candidates": {
                "white_x_width_multiplier": policy.outer.base_candidates.white_x_width_multiplier,
                "white_x_extra_ratio": policy.outer.base_candidates.white_x_extra_ratio,
                "candidate_max_area": policy.outer.base_candidates.candidate_max_area,
                "mask_expand_ratio": policy.outer.base_candidates.mask_expand_ratio,
                "mask_profiles": [
                    {
                        "name": profile.name,
                        "low": profile.low,
                        "high": profile.high,
                        "min_row_fraction": profile.min_row_fraction,
                        "min_col_fraction": profile.min_col_fraction,
                    }
                    for profile in policy.outer.base_candidates.mask_profiles
                ],
                "min_width_ratio": policy.outer.base_candidates.min_width_ratio,
                "min_height_ratio": policy.outer.base_candidates.min_height_ratio,
                "min_width_px": policy.outer.base_candidates.min_width_px,
                "min_height_px": policy.outer.base_candidates.min_height_px,
                "bw_not_white_threshold": policy.outer.base_candidates.bw_not_white_threshold,
                "bw_dark_threshold": policy.outer.base_candidates.bw_dark_threshold,
                "bw_min_fraction": policy.outer.base_candidates.bw_min_fraction,
                "bw_min_width_ratio": policy.outer.base_candidates.bw_min_width_ratio,
                "bw_min_height_ratio": policy.outer.base_candidates.bw_min_height_ratio,
                "bw_margin_ratio": policy.outer.base_candidates.bw_margin_ratio,
                "bw_margin_min": policy.outer.base_candidates.bw_margin_min,
                "white_border_ratio": policy.outer.base_candidates.white_border_ratio,
                "white_run_ratio": policy.outer.base_candidates.white_run_ratio,
                "white_run_min": policy.outer.base_candidates.white_run_min,
                "white_run_max": policy.outer.base_candidates.white_run_max,
                "white_dark_threshold": policy.outer.base_candidates.white_dark_threshold,
                "white_light_threshold": policy.outer.base_candidates.white_light_threshold,
                "white_min_width_ratio": policy.outer.base_candidates.white_min_width_ratio,
                "white_min_height_ratio": policy.outer.base_candidates.white_min_height_ratio,
                "white_margin_ratio": policy.outer.base_candidates.white_margin_ratio,
                "white_margin_min": policy.outer.base_candidates.white_margin_min,
            },
            "content_floating_outer": {
                "enabled": policy.outer.content_floating_outer.enabled,
                "ratio_extras": list(policy.outer.content_floating_outer.ratio_extras),
                "content_threshold": policy.outer.content_floating_outer.content_threshold,
                "content_margin_ratio": policy.outer.content_floating_outer.content_margin_ratio,
                "content_margin_min": policy.outer.content_floating_outer.content_margin_min,
                "content_margin_max": policy.outer.content_floating_outer.content_margin_max,
                "min_width_ratio": policy.outer.content_floating_outer.min_width_ratio,
                "max_candidates": policy.outer.content_floating_outer.max_candidates,
            },
            "edge_anchor_outer": {
                "mode": policy.outer.edge_anchor_outer.mode,
                "partial_center_ratio": policy.outer.edge_anchor_outer.partial_center_ratio,
                "ratio_extras": list(policy.outer.edge_anchor_outer.ratio_extras),
                "content_threshold": policy.outer.edge_anchor_outer.content_threshold,
                "content_margin_ratio": policy.outer.edge_anchor_outer.content_margin_ratio,
                "content_margin_min": policy.outer.edge_anchor_outer.content_margin_min,
                "content_margin_max": policy.outer.edge_anchor_outer.content_margin_max,
                "min_width_ratio": policy.outer.edge_anchor_outer.min_width_ratio,
                "max_candidates": policy.outer.edge_anchor_outer.max_candidates,
            },
            "separator_first": policy.outer.separator_first,
            "separator_geometry": policy.outer.separator_geometry,
            "separator_outer_allow_oversized_band": policy.outer.separator_outer_allow_oversized_band,
            "separator_outer_oversized_band_max_ratio": policy.outer.separator_outer_oversized_band_max_ratio,
            "separator_outer_oversized_band_score_penalty": policy.outer.separator_outer_oversized_band_score_penalty,
            "separator_gap_search_max_width_ratio": policy.outer.separator_gap_search_max_width_ratio,
            "separator_outer_band": {
                "min_score": policy.outer.separator_outer_band.min_score,
                "band_score": policy.outer.separator_outer_band.band_score,
                "min_width_ratio": policy.outer.separator_outer_band.min_width_ratio,
                "max_width_ratio": policy.outer.separator_outer_band.max_width_ratio,
                "spacing_min_ratio": policy.outer.separator_outer_band.spacing_min_ratio,
                "spacing_max_ratio": policy.outer.separator_outer_band.spacing_max_ratio,
                "frame_error_max": policy.outer.separator_outer_band.frame_error_max,
                "edge_margin_ratio": policy.outer.separator_outer_band.edge_margin_ratio,
                "source_candidate_count": policy.outer.separator_outer_band.source_candidate_count,
                "band_candidate_count": policy.outer.separator_outer_band.band_candidate_count,
                "pair_candidate_count": policy.outer.separator_outer_band.pair_candidate_count,
                "max_candidates": policy.outer.separator_outer_band.max_candidates,
            },
            "separator_geometry_outer": {
                "required_count": policy.outer.separator_geometry_outer.required_count,
                "source_candidate_count": policy.outer.separator_geometry_outer.source_candidate_count,
                "margin_ratios": list(policy.outer.separator_geometry_outer.margin_ratios),
                "max_candidates": policy.outer.separator_geometry_outer.max_candidates,
            },
            "dark_band": policy.outer.dark_band,
            "format_geometry_retry": {
                "enabled": policy.outer.format_geometry_retry.enabled,
                "ratio_tolerance": policy.outer.format_geometry_retry.ratio_tolerance,
                "min_shrink_ratio": policy.outer.format_geometry_retry.min_shrink_ratio,
                "max_shrink_ratio": policy.outer.format_geometry_retry.max_shrink_ratio,
                "content_margin_ratio": policy.outer.format_geometry_retry.content_margin_ratio,
                "content_margin_min": policy.outer.format_geometry_retry.content_margin_min,
                "content_margin_max": policy.outer.format_geometry_retry.content_margin_max,
            },
            "grid_refine": {
                "shift_ratio": policy.outer.grid_refine.shift_ratio,
                "shift_min": policy.outer.grid_refine.shift_min,
                "shift_max": policy.outer.grid_refine.shift_max,
                "max_width_change": policy.outer.grid_refine.max_width_change,
            },
            "short_axis_aspect_retry": {
                "enabled": policy.outer.short_axis_aspect_retry.enabled,
                "min_error": policy.outer.short_axis_aspect_retry.min_error,
                "target_aspect": policy.outer.short_axis_aspect_retry.target_aspect,
                "margin_ratio": policy.outer.short_axis_aspect_retry.margin_ratio,
                "margin_min": policy.outer.short_axis_aspect_retry.margin_min,
                "margin_max": policy.outer.short_axis_aspect_retry.margin_max,
            },
            "content_alignment": {
                "white_edge_long_ratio": policy.outer.content_alignment.white_edge_long_ratio,
                "white_edge_long_min": policy.outer.content_alignment.white_edge_long_min,
                "white_edge_long_max": policy.outer.content_alignment.white_edge_long_max,
                "long_gate_ratio": policy.outer.content_alignment.long_gate_ratio,
                "long_gate_min": policy.outer.content_alignment.long_gate_min,
                "long_gate_max": policy.outer.content_alignment.long_gate_max,
                "short_gate_ratio": policy.outer.content_alignment.short_gate_ratio,
                "short_gate_min": policy.outer.content_alignment.short_gate_min,
                "short_gate_max": policy.outer.content_alignment.short_gate_max,
                "long_excess_ratio": policy.outer.content_alignment.long_excess_ratio,
                "long_gate_excess_ratio": policy.outer.content_alignment.long_gate_excess_ratio,
                "short_excess_ratio": policy.outer.content_alignment.short_excess_ratio,
                "short_requires_hard_anchors": policy.outer.content_alignment.short_requires_hard_anchors,
                "short_content_height_max": policy.outer.content_alignment.short_content_height_max,
                "content_width_min": policy.outer.content_alignment.content_width_min,
                "edge_short_ratio": policy.outer.content_alignment.edge_short_ratio,
                "edge_dark_max": policy.outer.content_alignment.edge_dark_max,
                "border_band_ratio": policy.outer.content_alignment.border_band_ratio,
                "margin_x_ratio": policy.outer.content_alignment.margin_x_ratio,
                "margin_x_min": policy.outer.content_alignment.margin_x_min,
                "margin_x_max": policy.outer.content_alignment.margin_x_max,
                "margin_y_ratio": policy.outer.content_alignment.margin_y_ratio,
                "margin_y_min": policy.outer.content_alignment.margin_y_min,
                "margin_y_max": policy.outer.content_alignment.margin_y_max,
                "long_margin_ratio": policy.outer.content_alignment.long_margin_ratio,
                "long_margin_cap_ratio": policy.outer.content_alignment.long_margin_cap_ratio,
                "long_margin_cap_min": policy.outer.content_alignment.long_margin_cap_min,
                "long_margin_cap_max": policy.outer.content_alignment.long_margin_cap_max,
                "short_margin_ratio": policy.outer.content_alignment.short_margin_ratio,
                "short_margin_cap_ratio": policy.outer.content_alignment.short_margin_cap_ratio,
                "short_margin_cap_min": policy.outer.content_alignment.short_margin_cap_min,
                "short_margin_cap_max": policy.outer.content_alignment.short_margin_cap_max,
            },
            "dark_band_outer": {
                "mode": policy.outer.dark_band_outer.mode,
                "required_count": policy.outer.dark_band_outer.required_count,
                "threshold_ratio": policy.outer.dark_band_outer.threshold_ratio,
                "threshold_span_ratio": policy.outer.dark_band_outer.threshold_span_ratio,
                "min_width_ratio": policy.outer.dark_band_outer.min_width_ratio,
                "max_width_ratio": policy.outer.dark_band_outer.max_width_ratio,
                "core_width_cap_ratio": policy.outer.dark_band_outer.core_width_cap_ratio,
                "spacing_min_ratio": policy.outer.dark_band_outer.spacing_min_ratio,
                "spacing_max_ratio": policy.outer.dark_band_outer.spacing_max_ratio,
                "source_candidate_count": policy.outer.dark_band_outer.source_candidate_count,
                "max_candidates": policy.outer.dark_band_outer.max_candidates,
                "full_selection_enabled": policy.outer.dark_band_outer.full_selection_enabled,
                "full_selection_strip_modes": list(
                    policy.outer.dark_band_outer.full_selection_strip_modes
                ),
                "full_selection_requires_required_count": (
                    policy.outer.dark_band_outer.full_selection_requires_required_count
                ),
                "full_selection_requires_help": policy.outer.dark_band_outer.full_selection_requires_help,
                "full_selection_required_support": policy.outer.dark_band_outer.full_selection_required_support,
                "full_selection_allow_equal_gaps": policy.outer.dark_band_outer.full_selection_allow_equal_gaps,
                "full_selection_help_supports": list(policy.outer.dark_band_outer.full_selection_help_supports),
                "full_selection_help_reasons": list(policy.outer.dark_band_outer.full_selection_help_reasons),
            },
            "retries": list(policy.outer.retries),
        },
        "separator": {
            "gate_profile": policy.separator.gate.profile,
            "hard_required_all_gaps": policy.separator.hard_required_all_gaps,
            "wide_retry": policy.separator.wide_retry,
            "wide_retry_max_width_ratio": policy.separator.wide_retry_max_width_ratio,
            "wide_separator_confidence_cap": policy.separator.wide_separator_confidence_cap,
            "geometry_support_modes": list(policy.separator.geometry_support_modes),
            "geometry_support": {
                "wide_geometry": {
                    "enabled": policy.separator.geometry_support.wide_geometry.enabled,
                    "min_hard_ratio": policy.separator.geometry_support.wide_geometry.min_hard_ratio,
                    "min_joint_score": policy.separator.geometry_support.wide_geometry.min_joint_score,
                    "allow_grid": policy.separator.geometry_support.wide_geometry.allow_grid,
                    "max_equal_gaps": policy.separator.geometry_support.wide_geometry.max_equal_gaps,
                    "max_width_cv": policy.separator.geometry_support.wide_geometry.max_width_cv,
                    "required_content_support": policy.separator.geometry_support.wide_geometry.required_content_support,
                    "max_outer_area_ratio": policy.separator.geometry_support.wide_geometry.max_outer_area_ratio,
                },
                "stable_grid": {
                    "enabled": policy.separator.geometry_support.stable_grid.enabled,
                    "min_hard_ratio": policy.separator.geometry_support.stable_grid.min_hard_ratio,
                    "min_joint_score": policy.separator.geometry_support.stable_grid.min_joint_score,
                    "allow_grid": policy.separator.geometry_support.stable_grid.allow_grid,
                    "max_equal_gaps": policy.separator.geometry_support.stable_grid.max_equal_gaps,
                    "max_width_cv": policy.separator.geometry_support.stable_grid.max_width_cv,
                    "required_content_support": policy.separator.geometry_support.stable_grid.required_content_support,
                    "max_outer_area_ratio": policy.separator.geometry_support.stable_grid.max_outer_area_ratio,
                },
            },
            "profile": {
                "top_ratio": policy.separator.profile.top_ratio,
                "bottom_ratio": policy.separator.profile.bottom_ratio,
                "segments": policy.separator.profile.segments,
                "dark_threshold": policy.separator.profile.dark_threshold,
                "light_threshold": policy.separator.profile.light_threshold,
                "consistency_percentile": policy.separator.profile.consistency_percentile,
                "average_weight": policy.separator.profile.average_weight,
                "consistency_weight": policy.separator.profile.consistency_weight,
                "std_norm": policy.separator.profile.std_norm,
                "dark_soft_mean": policy.separator.profile.dark_soft_mean,
                "light_soft_mean": policy.separator.profile.light_soft_mean,
                "light_soft_span": policy.separator.profile.light_soft_span,
                "soft_weight": policy.separator.profile.soft_weight,
                "uniform_base": policy.separator.profile.uniform_base,
                "uniform_weight": policy.separator.profile.uniform_weight,
                "gradient_weight": policy.separator.profile.gradient_weight,
                "smooth_ratio": policy.separator.profile.smooth_ratio,
                "smooth_min": policy.separator.profile.smooth_min,
            },
            "edge_refine_profile": {
                "top_ratio": policy.separator.edge_refine_profile.top_ratio,
                "bottom_ratio": policy.separator.edge_refine_profile.bottom_ratio,
                "mean_weight": policy.separator.edge_refine_profile.mean_weight,
                "p75_weight": policy.separator.edge_refine_profile.p75_weight,
                "smooth_ratio": policy.separator.edge_refine_profile.smooth_ratio,
                "smooth_min": policy.separator.edge_refine_profile.smooth_min,
                "high_percentile": policy.separator.edge_refine_profile.high_percentile,
                "background_dark_threshold": policy.separator.edge_refine_profile.background_dark_threshold,
                "background_light_threshold": policy.separator.edge_refine_profile.background_light_threshold,
                "y_edge_weight": policy.separator.edge_refine_profile.y_edge_weight,
                "activity_percentile": policy.separator.edge_refine_profile.activity_percentile,
            },
            "edge_pair": {
                "window_ratio": policy.separator.edge_pair.window_ratio,
                "min_gutter_ratio": policy.separator.edge_pair.min_gutter_ratio,
                "max_gutter_ratio": policy.separator.edge_pair.max_gutter_ratio,
                "min_strength": policy.separator.edge_pair.min_strength,
                "min_background": policy.separator.edge_pair.min_background,
                "min_quality_for_model_gap": policy.separator.edge_pair.min_quality_for_model_gap,
                "min_quality_for_hard_gap": policy.separator.edge_pair.min_quality_for_hard_gap,
                "hard_gap_quality_ratio": policy.separator.edge_pair.hard_gap_quality_ratio,
                "max_hard_shift_ratio": policy.separator.edge_pair.max_hard_shift_ratio,
            },
            "hard_gap_trust": {
                "guard_ratio": policy.separator.hard_gap_trust.guard_ratio,
                "guard_min": policy.separator.hard_gap_trust.guard_min,
                "guard_max": policy.separator.hard_gap_trust.guard_max,
                "narrow_ratio": policy.separator.hard_gap_trust.narrow_ratio,
                "narrow_min": policy.separator.hard_gap_trust.narrow_min,
                "narrow_max": policy.separator.hard_gap_trust.narrow_max,
                "model_delta_ratio": policy.separator.hard_gap_trust.model_delta_ratio,
                "geometry_width_ratio": policy.separator.hard_gap_trust.geometry_width_ratio,
                "strong_min_score": policy.separator.hard_gap_trust.strong_min_score,
                "strong_width_min": policy.separator.hard_gap_trust.strong_width_min,
                "strong_width_max": policy.separator.hard_gap_trust.strong_width_max,
                "narrow_ok_score": policy.separator.hard_gap_trust.narrow_ok_score,
                "narrow_ok_width_min": policy.separator.hard_gap_trust.narrow_ok_width_min,
                "narrow_ok_width_max": policy.separator.hard_gap_trust.narrow_ok_width_max,
                "model_conflict_score": policy.separator.hard_gap_trust.model_conflict_score,
                "core_content_threshold": policy.separator.hard_gap_trust.core_content_threshold,
                "core_dark_threshold": policy.separator.hard_gap_trust.core_dark_threshold,
                "dark_mean_max": policy.separator.hard_gap_trust.dark_mean_max,
                "dark_fraction_min": policy.separator.hard_gap_trust.dark_fraction_min,
                "dark_activity_max": policy.separator.hard_gap_trust.dark_activity_max,
                "strong_core_content_max": policy.separator.hard_gap_trust.strong_core_content_max,
                "weak_mean_min": policy.separator.hard_gap_trust.weak_mean_min,
                "weak_content_min": policy.separator.hard_gap_trust.weak_content_min,
                "frame_border_width_ratio": policy.separator.hard_gap_trust.frame_border_width_ratio,
                "continuity_min": policy.separator.hard_gap_trust.continuity_min,
                "activity_min": policy.separator.hard_gap_trust.activity_min,
            },
            "nearby_correction": {
                "enabled": policy.separator.nearby_correction.enabled,
                "window_ratio": policy.separator.nearby_correction.window_ratio,
                "window_min": policy.separator.nearby_correction.window_min,
                "window_max": policy.separator.nearby_correction.window_max,
                "exclude_ratio": policy.separator.nearby_correction.exclude_ratio,
                "exclude_min": policy.separator.nearby_correction.exclude_min,
                "exclude_max": policy.separator.nearby_correction.exclude_max,
                "max_width_ratio": policy.separator.nearby_correction.max_width_ratio,
                "max_width_min": policy.separator.nearby_correction.max_width_min,
                "max_width_max": policy.separator.nearby_correction.max_width_max,
                "distance_ratio": policy.separator.nearby_correction.distance_ratio,
                "score_add": policy.separator.nearby_correction.score_add,
                "score_multiplier": policy.separator.nearby_correction.score_multiplier,
                "local_gain_ratio": policy.separator.nearby_correction.local_gain_ratio,
                "local_gain_min": policy.separator.nearby_correction.local_gain_min,
                "local_gain_max": policy.separator.nearby_correction.local_gain_max,
                "width_cv_slack": policy.separator.nearby_correction.width_cv_slack,
            },
            "robust_grid": {
                "constrain_full_shift_ratio": policy.separator.robust_grid.constrain_full_shift_ratio,
                "constrain_partial_shift_ratio": policy.separator.robust_grid.constrain_partial_shift_ratio,
                "constrain_shift_min": policy.separator.robust_grid.constrain_shift_min,
                "constrain_shift_max": policy.separator.robust_grid.constrain_shift_max,
                "reliable_min_score": policy.separator.robust_grid.reliable_min_score,
                "min_reliable": policy.separator.robust_grid.min_reliable,
                "pitch_min_ratio": policy.separator.robust_grid.pitch_min_ratio,
                "pitch_max_ratio": policy.separator.robust_grid.pitch_max_ratio,
                "full_tolerance_ratio": policy.separator.robust_grid.full_tolerance_ratio,
                "partial_tolerance_ratio": policy.separator.robust_grid.partial_tolerance_ratio,
                "tolerance_min": policy.separator.robust_grid.tolerance_min,
                "tolerance_max": policy.separator.robust_grid.tolerance_max,
                "reject_residual_ratio": policy.separator.robust_grid.reject_residual_ratio,
                "full_shift_ratio": policy.separator.robust_grid.full_shift_ratio,
                "partial_shift_ratio": policy.separator.robust_grid.partial_shift_ratio,
                "shift_min": policy.separator.robust_grid.shift_min,
                "shift_max": policy.separator.robust_grid.shift_max,
                "hard_keep_ratio": policy.separator.robust_grid.hard_keep_ratio,
                "hard_keep_min": policy.separator.robust_grid.hard_keep_min,
                "hard_keep_max": policy.separator.robust_grid.hard_keep_max,
                "hard_protect_ratio": policy.separator.robust_grid.hard_protect_ratio,
                "hard_protect_min": policy.separator.robust_grid.hard_protect_min,
                "hard_protect_max": policy.separator.robust_grid.hard_protect_max,
            },
            "gap_search": {
                "radius_ratio": policy.separator.gap_search.radius_ratio,
                "radius_min": policy.separator.gap_search.radius_min,
                "radius_max": policy.separator.gap_search.radius_max,
                "max_width_ratio": policy.separator.gap_search.max_width_ratio,
                "max_width_min": policy.separator.gap_search.max_width_min,
                "max_width_max": policy.separator.gap_search.max_width_max,
                "min_width_ratio": policy.separator.gap_search.min_width_ratio,
                "min_width_min": policy.separator.gap_search.min_width_min,
                "min_width_max": policy.separator.gap_search.min_width_max,
                "guard_ratio": policy.separator.gap_search.guard_ratio,
                "guard_min": policy.separator.gap_search.guard_min,
                "guard_max": policy.separator.gap_search.guard_max,
                "min_score": policy.separator.gap_search.min_score,
                "peak_multiplier": policy.separator.gap_search.peak_multiplier,
                "band_multiplier": policy.separator.gap_search.band_multiplier,
                "wide_min_mean": policy.separator.gap_search.wide_min_mean,
                "wide_min_prominence": policy.separator.gap_search.wide_min_prominence,
            },
            "enhanced": {
                "min_score": policy.separator.enhanced.min_score,
                "max_width_ratio": policy.separator.enhanced.max_width_ratio,
                "max_width_min": policy.separator.enhanced.max_width_min,
                "max_width_max": policy.separator.enhanced.max_width_max,
                "max_shift_ratio": policy.separator.enhanced.max_shift_ratio,
                "max_shift_min": policy.separator.enhanced.max_shift_min,
                "max_shift_max": policy.separator.enhanced.max_shift_max,
                "auto_low_score": policy.separator.enhanced.auto_low_score,
            },
            "gate": {
                "profile": policy.separator.gate.profile,
                "needed_hard_max": policy.separator.gate.needed_hard_max,
                "max_equal_gaps_floor": policy.separator.gate.max_equal_gaps_floor,
                "allow_geometry_support": policy.separator.gate.allow_geometry_support,
                "hard_required_all_gaps": policy.separator.gate.hard_required_all_gaps,
                "edge_pair_min_score_without_wide": policy.separator.gate.edge_pair_min_score_without_wide,
                "edge_pair_min_score_with_wide": policy.separator.gate.edge_pair_min_score_with_wide,
                "min_wide_gaps_for_auto": policy.separator.gate.min_wide_gaps_for_auto,
                "score_min_hard_gaps": policy.separator.gate.score_min_hard_gaps,
                "score_max_equal_gaps_floor": policy.separator.gate.score_max_equal_gaps_floor,
                "low_hard_confidence_cap": policy.separator.gate.low_hard_confidence_cap,
                "mostly_equal_confidence_cap": policy.separator.gate.mostly_equal_confidence_cap,
                "allow_full_detected_geometry": policy.separator.gate.allow_full_detected_geometry,
                "leading_grid_failure": {
                    "enabled": policy.separator.gate.leading_grid_failure.enabled,
                    "min_expected_gaps": policy.separator.gate.leading_grid_failure.min_expected_gaps,
                    "leading_count": policy.separator.gate.leading_grid_failure.leading_count,
                    "low_score": policy.separator.gate.leading_grid_failure.low_score,
                    "very_low_score": policy.separator.gate.leading_grid_failure.very_low_score,
                    "very_low_count": policy.separator.gate.leading_grid_failure.very_low_count,
                    "max_hard_gaps": policy.separator.gate.leading_grid_failure.max_hard_gaps,
                },
            },
        },
        "content": {
            "can_auto_pass_alone": policy.content.can_auto_pass_alone,
            "required_support_for_auto": policy.content.required_support_for_auto,
            "validates_candidates": policy.content.validates_candidates,
            "support_coverage_norm": policy.content.support_coverage_norm,
            "support_mean_norm": policy.content.support_mean_norm,
            "support_aspect_norm": policy.content.support_aspect_norm,
            "support_coverage_weight": policy.content.support_coverage_weight,
            "support_mean_weight": policy.content.support_mean_weight,
            "support_aspect_weight": policy.content.support_aspect_weight,
            "support_gate_ok": policy.content.support_gate_ok,
            "support_gate_weak": policy.content.support_gate_weak,
            "support_gate_low_content": policy.content.support_gate_low_content,
            "support_gate_aspect_conflict": policy.content.support_gate_aspect_conflict,
            "support_gate_unknown": policy.content.support_gate_unknown,
            "evidence": {
                "percentile": policy.content.evidence.percentile,
                "threshold_multiplier": policy.content.evidence.threshold_multiplier,
                "threshold_min": policy.content.evidence.threshold_min,
                "threshold_max": policy.content.evidence.threshold_max,
                "aspect_ok_max": policy.content.evidence.aspect_ok_max,
                "present_mean_min": policy.content.evidence.present_mean_min,
                "present_coverage_min": policy.content.evidence.present_coverage_min,
            },
            "profile": {
                "smooth_ratio": policy.content.profile.smooth_ratio,
                "min_run_ratio": policy.content.profile.min_run_ratio,
                "threshold_min": policy.content.profile.threshold_min,
                "threshold_max": policy.content.profile.threshold_max,
                "p35_weight": policy.content.profile.p35_weight,
                "p65_multiplier": policy.content.profile.p65_multiplier,
            },
            "mask": {
                "p55_weight": policy.content.mask.p55_weight,
                "p75_multiplier": policy.content.mask.p75_multiplier,
                "threshold_min": policy.content.mask.threshold_min,
                "threshold_max": policy.content.mask.threshold_max,
                "percentiles": list(policy.content.mask.percentiles),
                "bbox_min_fraction": policy.content.mask.bbox_min_fraction,
                "outer_min_width_ratio": policy.content.mask.outer_min_width_ratio,
                "outer_min_height_ratio": policy.content.mask.outer_min_height_ratio,
                "outer_min_width_px": policy.content.mask.outer_min_width_px,
                "outer_min_height_px": policy.content.mask.outer_min_height_px,
                "outer_expand_ratio": policy.content.mask.outer_expand_ratio,
            },
            "candidate": {
                "expected_width_min_px": policy.content.candidate.expected_width_min_px,
                "coverage_weight": policy.content.candidate.coverage_weight,
                "mean_weight": policy.content.candidate.mean_weight,
                "run_weight": policy.content.candidate.run_weight,
                "aspect_weight": policy.content.candidate.aspect_weight,
                "coverage_norm": policy.content.candidate.coverage_norm,
                "mean_norm": policy.content.candidate.mean_norm,
                "aspect_norm": policy.content.candidate.aspect_norm,
                "weak_coverage": policy.content.candidate.weak_coverage,
                "aspect_uncertain": policy.content.candidate.aspect_uncertain,
                "grid_fallback_cap": policy.content.candidate.grid_fallback_cap,
                "run_mismatch_cap": policy.content.candidate.run_mismatch_cap,
                "runs_incomplete_cap": policy.content.candidate.runs_incomplete_cap,
                "weak_coverage_cap": policy.content.candidate.weak_coverage_cap,
                "aspect_uncertain_cap": policy.content.candidate.aspect_uncertain_cap,
            },
        },
        "gates": list(policy.gates.ordered_gates),
        "partial_holder": {
            "safe_extra_frames": policy.partial_holder.safe_extra_frames,
            "safe_extra_frames_strip_modes": list(
                policy.partial_holder.safe_extra_frames_strip_modes
            ),
            "requires_wide_like_gaps": policy.partial_holder.requires_wide_like_gaps,
            "checks_leading_content": policy.partial_holder.checks_leading_content,
            "checks_frame_content": policy.partial_holder.checks_frame_content,
            "min_count_35mm": policy.partial_holder.min_count_35mm,
            "min_count_small": policy.partial_holder.min_count_small,
            "min_hard_gaps": policy.partial_holder.min_hard_gaps,
            "min_hard_ratio": policy.partial_holder.min_hard_ratio,
            "max_equal_gaps": policy.partial_holder.max_equal_gaps,
            "max_width_cv": policy.partial_holder.max_width_cv,
            "min_joint_score": policy.partial_holder.min_joint_score,
            "min_content_score": policy.partial_holder.min_content_score,
            "min_geometry_score": policy.partial_holder.min_geometry_score,
            "wide_like_min_width_ratio": policy.partial_holder.wide_like_min_width_ratio,
            "leading_content_max_mean": policy.partial_holder.leading_content_max_mean,
            "leading_content_max_coverage": policy.partial_holder.leading_content_max_coverage,
            "leading_content_band_ratio": policy.partial_holder.leading_content_band_ratio,
            "min_frame_mean": policy.partial_holder.min_frame_mean,
            "min_frame_coverage": policy.partial_holder.min_frame_coverage,
            "max_frame_aspect_error": policy.partial_holder.max_frame_aspect_error,
        },
        "partial_edge_hint": {
            "window_ratio": policy.partial_edge_hint.window_ratio,
            "window_min": policy.partial_edge_hint.window_min,
            "window_max": policy.partial_edge_hint.window_max,
        },
        "scoring": {
            "confidence_threshold_default": policy.scoring.confidence_threshold_default,
            "hard_full_confidence_floor": policy.scoring.hard_full_confidence_floor,
            "geometry_weight": policy.scoring.geometry_weight,
            "content_weight": policy.scoring.content_weight,
            "separator_weight": policy.scoring.separator_weight,
            "separator_source_bias": policy.scoring.separator_source_bias,
            "no_auto_cap_full": policy.scoring.no_auto_cap_full,
            "no_auto_cap_partial": policy.scoring.no_auto_cap_partial,
            "competition_top_n": policy.scoring.competition_top_n,
            "competition_close_margin": policy.scoring.competition_close_margin,
            "base_detection": {
                "width_cv_norm": policy.scoring.base_detection.width_cv_norm,
                "gap_weight": policy.scoring.base_detection.gap_weight,
                "width_weight": policy.scoring.base_detection.width_weight,
                "outer_weight": policy.scoring.base_detection.outer_weight,
                "contrast_weight": policy.scoring.base_detection.contrast_weight,
                "outer_min_area": policy.scoring.base_detection.outer_min_area,
                "outer_max_area": policy.scoring.base_detection.outer_max_area,
                "outer_too_large": policy.scoring.base_detection.outer_too_large,
                "outer_uncertain_confidence": policy.scoring.base_detection.outer_uncertain_confidence,
                "contrast_min": policy.scoring.base_detection.contrast_min,
                "contrast_floor": policy.scoring.base_detection.contrast_floor,
                "full_width_cv": policy.scoring.base_detection.full_width_cv,
                "geometry_floor_tight_cv": policy.scoring.base_detection.geometry_floor_tight_cv,
                "geometry_floor_high": policy.scoring.base_detection.geometry_floor_high,
                "geometry_floor_low": policy.scoring.base_detection.geometry_floor_low,
                "unstable_width_cv": policy.scoring.base_detection.unstable_width_cv,
                "full_outer_min_area": policy.scoring.base_detection.full_outer_min_area,
                "low_confidence_floor": policy.scoring.base_detection.low_confidence_floor,
                "partial_one_cap": policy.scoring.base_detection.partial_one_cap,
                "partial_two_35mm_cap": policy.scoring.base_detection.partial_two_35mm_cap,
                "partial_general_cap": policy.scoring.base_detection.partial_general_cap,
                "outer_too_large_cap": policy.scoring.base_detection.outer_too_large_cap,
                "family_separator_uncertain_reason": (
                    policy.scoring.base_detection.family_separator_uncertain_reason
                ),
            },
            "geometry_support": {
                "width_cv_norm": policy.scoring.geometry_support.width_cv_norm,
                "outer_min_area": policy.scoring.geometry_support.outer_min_area,
                "outer_max_area": policy.scoring.geometry_support.outer_max_area,
                "outer_uncertain_score": policy.scoring.geometry_support.outer_uncertain_score,
                "aspect_norm": policy.scoring.geometry_support.aspect_norm,
                "no_aspect_score": policy.scoring.geometry_support.no_aspect_score,
                "width_weight": policy.scoring.geometry_support.width_weight,
                "outer_weight": policy.scoring.geometry_support.outer_weight,
                "aspect_weight": policy.scoring.geometry_support.aspect_weight,
                "count_weight": policy.scoring.geometry_support.count_weight,
            },
            "separator_support": {
                "model_grid_credit": policy.scoring.separator_support.model_grid_credit,
                "model_equal_credit": policy.scoring.separator_support.model_equal_credit,
                "hard_weight": policy.scoring.separator_support.hard_weight,
                "model_weight": policy.scoring.separator_support.model_weight,
                "no_expected_confidence_threshold": policy.scoring.separator_support.no_expected_confidence_threshold,
                "no_expected_confidence_cap": policy.scoring.separator_support.no_expected_confidence_cap,
            },
        },
        "selection": {
            "top_n": policy.candidate_selection.top_n,
            "close_margin": policy.candidate_selection.close_margin,
            "confidence_cap": policy.candidate_selection.confidence_cap,
            "content_mismatch_review": {
                "enabled": policy.candidate_selection.content_mismatch_review.enabled,
                "strip_modes": list(policy.candidate_selection.content_mismatch_review.strip_modes),
                "require_default_count": (
                    policy.candidate_selection.content_mismatch_review.require_default_count
                ),
                "required_best_source": policy.candidate_selection.content_mismatch_review.required_best_source,
                "required_review_reason": policy.candidate_selection.content_mismatch_review.required_review_reason,
                "candidate_source": policy.candidate_selection.content_mismatch_review.candidate_source,
                "min_hard_ratio": policy.candidate_selection.content_mismatch_review.min_hard_ratio,
                "max_equal_gaps": policy.candidate_selection.content_mismatch_review.max_equal_gaps,
                "required_content_support": policy.candidate_selection.content_mismatch_review.required_content_support,
                "override_reason": policy.candidate_selection.content_mismatch_review.override_reason,
            },
        },
        "candidate_run": {
            "equal_first_before_wide_retry": {
                "enabled": policy.candidate_run.equal_first_before_wide_retry.enabled,
                "requires_wide_geometry_support": (
                    policy.candidate_run.equal_first_before_wide_retry.requires_wide_geometry_support
                ),
                "strip_modes": list(policy.candidate_run.equal_first_before_wide_retry.strip_modes),
                "requires_default_count": (
                    policy.candidate_run.equal_first_before_wide_retry.requires_default_count
                ),
            },
            "content_candidate": {
                "enabled": policy.candidate_run.content_candidate.enabled,
                "skip_after_separator_auto": policy.candidate_run.content_candidate.skip_after_separator_auto,
                "separator_auto_skip_strip_modes": list(
                    policy.candidate_run.content_candidate.separator_auto_skip_strip_modes
                ),
                "separator_auto_skip_reason": (
                    policy.candidate_run.content_candidate.separator_auto_skip_reason
                ),
                "disabled_skip_reason": policy.candidate_run.content_candidate.disabled_skip_reason,
            },
            "fallback": {
                "use_outer_proposals": policy.candidate_run.fallback.use_outer_proposals,
                "strategies": list(policy.candidate_run.fallback.strategies),
            },
            "partial_stop": {
                "stop_after_safe_auto": policy.candidate_run.partial_stop.stop_after_safe_auto,
                "skip_content_after_safe_auto": policy.candidate_run.partial_stop.skip_content_after_safe_auto,
                "skip_content_after_safe_auto_strip_modes": list(
                    policy.candidate_run.partial_stop.skip_content_after_safe_auto_strip_modes
                ),
                "skip_content_after_safe_auto_reason": (
                    policy.candidate_run.partial_stop.skip_content_after_safe_auto_reason
                ),
            },
            "separator_geometry_competition": {
                "enabled": policy.candidate_run.separator_geometry_competition.enabled,
                "content_outer_max_median_aspect_strategies": list(
                    policy.candidate_run.separator_geometry_competition.content_outer_max_median_aspect_strategies
                ),
                "content_outer_max_median_aspect_strip_modes": list(
                    policy.candidate_run.separator_geometry_competition.content_outer_max_median_aspect_strip_modes
                ),
                "content_outer_max_median_aspect": (
                    policy.candidate_run.separator_geometry_competition.content_outer_max_median_aspect
                ),
                "general_min_median_aspect": policy.candidate_run.separator_geometry_competition.general_min_median_aspect,
            },
            "dark_band_retry": {
                "try_full_default_count": policy.candidate_run.dark_band_retry.try_full_default_count,
                "full_retry_strip_modes": list(
                    policy.candidate_run.dark_band_retry.full_retry_strip_modes
                ),
                "full_retry_requires_default_count": (
                    policy.candidate_run.dark_band_retry.full_retry_requires_default_count
                ),
                "partial_retry_strip_modes": list(
                    policy.candidate_run.dark_band_retry.partial_retry_strip_modes
                ),
                "try_partial_when_no_safe_wide_like_candidate": (
                    policy.candidate_run.dark_band_retry.try_partial_when_no_safe_wide_like_candidate
                ),
                "partial_retry_on_equal_gaps": policy.candidate_run.dark_band_retry.partial_retry_on_equal_gaps,
                "partial_retry_on_insufficient_wide_like_gaps": (
                    policy.candidate_run.dark_band_retry.partial_retry_on_insufficient_wide_like_gaps
                ),
            },
        },
        "postprocess": {
            "align_outer_to_content": policy.postprocess.align_outer_to_content,
            "retry_uncertain_outer": policy.postprocess.retry_uncertain_outer,
            "apply_output_bleed": policy.postprocess.apply_output_bleed,
            "apply_approved_geometry_adjustment": policy.postprocess.apply_approved_geometry_adjustment,
            "approved_geometry_adjustment": {
                "long_limit_ratio": policy.postprocess.approved_geometry_adjustment.long_limit_ratio,
                "long_limit_min": policy.postprocess.approved_geometry_adjustment.long_limit_min,
                "long_limit_max": policy.postprocess.approved_geometry_adjustment.long_limit_max,
                "min_ext_ratio": policy.postprocess.approved_geometry_adjustment.min_ext_ratio,
                "min_ext_min": policy.postprocess.approved_geometry_adjustment.min_ext_min,
                "min_ext_max": policy.postprocess.approved_geometry_adjustment.min_ext_max,
            },
            "outer_alignment_disabled_reason": policy.postprocess.outer_alignment_disabled_reason,
            "likely_partial_review_reason": policy.postprocess.likely_partial_review_reason,
            "outer_candidate_disagreement_review_reason": (
                policy.postprocess.outer_candidate_disagreement_review_reason
            ),
            "deskew_uncertain_review_reason": policy.postprocess.deskew_uncertain_review_reason,
            "content_aspect_conflict_cap": policy.postprocess.content_aspect_conflict_cap,
            "content_low_confidence_cap": policy.postprocess.content_low_confidence_cap,
            "outer_mismatch_cap": policy.postprocess.outer_mismatch_cap,
            "lucky_pass_risk_cap": policy.postprocess.lucky_pass_risk_cap,
        },
        "output": {
            "detection_long_axis_bleed": policy.output.detection_long_axis_bleed,
            "detection_short_axis_bleed": policy.output.detection_short_axis_bleed,
            "output_long_axis_bleed_default": policy.output.output_long_axis_bleed_default,
            "output_short_axis_bleed_default": policy.output.output_short_axis_bleed_default,
            "overlap_risk_long_axis_bleed": policy.output.overlap_risk_long_axis_bleed,
            "edge_bleed_protection": {
                "enabled": policy.output.edge_bleed_protection.enabled,
                "guard_ratio": policy.output.edge_bleed_protection.guard_ratio,
                "guard_min": policy.output.edge_bleed_protection.guard_min,
                "guard_max": policy.output.edge_bleed_protection.guard_max,
            },
        },
        "diagnostics": {
            "overlap_bleed_risk": {
                "enabled": policy.diagnostics.overlap_bleed_risk.enabled,
                "mean_min": policy.diagnostics.overlap_bleed_risk.mean_min,
                "weak_continuity": policy.diagnostics.overlap_bleed_risk.weak_continuity,
                "weak_activity": policy.diagnostics.overlap_bleed_risk.weak_activity,
                "medium_continuity": policy.diagnostics.overlap_bleed_risk.medium_continuity,
                "medium_activity": policy.diagnostics.overlap_bleed_risk.medium_activity,
                "strong_continuity": policy.diagnostics.overlap_bleed_risk.strong_continuity,
                "strong_activity": policy.diagnostics.overlap_bleed_risk.strong_activity,
            },
            "debug_gap_overlay": {
                "overlap_tolerance_ratio": policy.diagnostics.debug_gap_overlay.overlap_tolerance_ratio,
                "overlap_tolerance_min": policy.diagnostics.debug_gap_overlay.overlap_tolerance_min,
                "overlap_tolerance_max": policy.diagnostics.debug_gap_overlay.overlap_tolerance_max,
                "tick_length_ratio": policy.diagnostics.debug_gap_overlay.tick_length_ratio,
                "tick_length_min": policy.diagnostics.debug_gap_overlay.tick_length_min,
                "hard_line_width": policy.diagnostics.debug_gap_overlay.hard_line_width,
                "model_line_width": policy.diagnostics.debug_gap_overlay.model_line_width,
                "diagnostic_line_width": policy.diagnostics.debug_gap_overlay.diagnostic_line_width,
            },
            "nearby_separator": {
                "window_ratio": policy.diagnostics.nearby_separator.window_ratio,
                "window_min": policy.diagnostics.nearby_separator.window_min,
                "window_max": policy.diagnostics.nearby_separator.window_max,
                "exclude_ratio": policy.diagnostics.nearby_separator.exclude_ratio,
                "exclude_min": policy.diagnostics.nearby_separator.exclude_min,
                "exclude_max": policy.diagnostics.nearby_separator.exclude_max,
                "max_width_ratio": policy.diagnostics.nearby_separator.max_width_ratio,
                "max_width_min": policy.diagnostics.nearby_separator.max_width_min,
                "max_width_max": policy.diagnostics.nearby_separator.max_width_max,
                "detail_score_add": policy.diagnostics.nearby_separator.detail_score_add,
                "detail_score_multiplier": policy.diagnostics.nearby_separator.detail_score_multiplier,
            },
            "lucky_pass_risk": {
                "enabled": policy.diagnostics.lucky_pass_risk.enabled,
                "model_gap_support_min": policy.diagnostics.lucky_pass_risk.model_gap_support_min,
                "model_gap_support_weight": policy.diagnostics.lucky_pass_risk.model_gap_support_weight,
                "minor_model_gap_support_weight": policy.diagnostics.lucky_pass_risk.minor_model_gap_support_weight,
                "limited_strong_hard_max": policy.diagnostics.lucky_pass_risk.limited_strong_hard_max,
                "limited_strong_hard_weight": policy.diagnostics.lucky_pass_risk.limited_strong_hard_weight,
                "very_limited_strong_hard_max": policy.diagnostics.lucky_pass_risk.very_limited_strong_hard_max,
                "very_limited_strong_hard_weight": policy.diagnostics.lucky_pass_risk.very_limited_strong_hard_weight,
                "suspicious_hard_weight": policy.diagnostics.lucky_pass_risk.suspicious_hard_weight,
                "strong_overlap_weight": policy.diagnostics.lucky_pass_risk.strong_overlap_weight,
                "combo_weight": policy.diagnostics.lucky_pass_risk.combo_weight,
                "unstable_width_cv": policy.diagnostics.lucky_pass_risk.unstable_width_cv,
                "unstable_width_weight": policy.diagnostics.lucky_pass_risk.unstable_width_weight,
                "mild_width_cv": policy.diagnostics.lucky_pass_risk.mild_width_cv,
                "mild_width_weight": policy.diagnostics.lucky_pass_risk.mild_width_weight,
                "strong_hard_credit_min": policy.diagnostics.lucky_pass_risk.strong_hard_credit_min,
                "strong_hard_credit": policy.diagnostics.lucky_pass_risk.strong_hard_credit,
                "stable_width_cv": policy.diagnostics.lucky_pass_risk.stable_width_cv,
                "stable_model_gap_min": policy.diagnostics.lucky_pass_risk.stable_model_gap_min,
                "stable_geometry_credit": policy.diagnostics.lucky_pass_risk.stable_geometry_credit,
                "risk_threshold": policy.diagnostics.lucky_pass_risk.risk_threshold,
            },
            "debug_panels": list(policy.diagnostics.debug_panels),
            "debug_panel_titles": {
                panel.panel_id: panel.title
                for panel in policy.diagnostics.debug_panel_titles
            },
        },
        "report": {
            "schema_version": policy.report.schema_version,
            "sections": list(policy.report.sections),
        },
        "notes": list(policy.notes),
    }
