from __future__ import annotations

SEPARATOR_GATE_PROFILE_MIN_HARD_WITH_EQUAL_CAP = "min_hard_with_equal_cap"
SEPARATOR_GATE_PROFILE_ALL_INTERNAL_GAPS_HARD = "all_internal_gaps_hard"
SEPARATOR_GATE_PROFILE_GEOMETRY_SUPPORT = "geometry_support"

SEPARATOR_GATE_PROFILES = (
    SEPARATOR_GATE_PROFILE_MIN_HARD_WITH_EQUAL_CAP,
    SEPARATOR_GATE_PROFILE_ALL_INTERNAL_GAPS_HARD,
    SEPARATOR_GATE_PROFILE_GEOMETRY_SUPPORT,
)


__all__ = [
    "SEPARATOR_GATE_PROFILE_ALL_INTERNAL_GAPS_HARD",
    "SEPARATOR_GATE_PROFILE_GEOMETRY_SUPPORT",
    "SEPARATOR_GATE_PROFILE_MIN_HARD_WITH_EQUAL_CAP",
    "SEPARATOR_GATE_PROFILES",
]
