"""Canonical file manifest for user-facing X5 Crop release archives."""

from __future__ import annotations


# (archive path, repository source path). ``None`` means generated by the builder.
RELEASE_FILES: tuple[tuple[str, str | None], ...] = (
    ("X5_Crop.py", None),
    ("X5_Crop_Mac.command", "X5_Crop_Mac.command"),
    ("X5_Crop_win.bat", "X5_Crop_win.bat"),
    ("README.txt", "README.md"),
    ("快速启动_Quick_Start.txt", "快速启动_Quick_Start.md"),
    ("install/X5_Crop_Mac_install.command", "install/X5_Crop_Mac_install.command"),
    ("install/X5_Crop_win_install.bat", "install/X5_Crop_win_install.bat"),
    ("install/X5_Crop_Mac_uninstall.command", "install/X5_Crop_Mac_uninstall.command"),
    ("install/X5_Crop_win_uninstall.bat", "install/X5_Crop_win_uninstall.bat"),
)

RELEASE_PATHS = tuple(archive_path for archive_path, _ in RELEASE_FILES)
